name: Metrics

on:
  schedule: [{cron: "0 0 * * 1"}] # Atualiza toda segunda-feira
  workflow_dispatch: # Permite execução manual

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
